[ 2024-12-25 13:09:51,683 ] 39 root - INFO - Start data Ingestion
[ 2024-12-25 13:09:56,191 ] 65 root - INFO - Performed train test split on the dataframe
[ 2024-12-25 13:09:56,192 ] 67 root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[ 2024-12-25 13:09:56,199 ] 75 root - INFO - Exporting train and test file path.
[ 2024-12-25 13:09:56,473 ] 84 root - INFO - Exported train and test file path.
[ 2024-12-25 13:09:56,473 ] 42 root - INFO - Data Ingestion completed and artifact: DataIngestionArtifact(trained_file_path='Artifacts/12_25_2024_13_05_11/data_ingestion/ingested/train.csv', test_file_path='Artifacts/12_25_2024_13_05_11/data_ingestion/ingested/test.csv')
[ 2024-12-25 13:09:56,496 ] 52 root - INFO - Initiate the data Validation
[ 2024-12-25 13:10:01,789 ] 33 root - INFO - Required number of columns:2
[ 2024-12-25 13:10:01,790 ] 34 root - INFO - Data frame has columns:1
[ 2024-12-25 13:10:01,790 ] 33 root - INFO - Required number of columns:2
[ 2024-12-25 13:10:01,791 ] 34 root - INFO - Data frame has columns:1
[ 2024-12-25 13:10:01,858 ] 55 root - INFO - Entered initiate_data_transformation method of DataTransformation class
[ 2024-12-25 13:10:01,858 ] 57 root - INFO - Starting data transformation
[ 2024-12-25 13:10:01,909 ] 45 root - INFO - Initialise KNNImputer with {'missing_values': nan, 'n_neighbors': 3, 'weights': 'uniform'}
[ 2024-12-25 13:10:01,989 ] 51 root - INFO - Entered the save_object method of MainUtils class
[ 2024-12-25 13:10:02,032 ] 55 root - INFO - Exited the save_object method of MainUtils class
[ 2024-12-25 13:10:02,033 ] 51 root - INFO - Entered the save_object method of MainUtils class
[ 2024-12-25 13:10:02,072 ] 55 root - INFO - Exited the save_object method of MainUtils class
[ 2024-12-25 13:23:04,536 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f41a0173620>, 'Connection to ec2-54-221-47-33.compute-1.amazonaws.com timed out. (connect timeout=120)')': /api/2.0/mlflow/runs/create
[ 2024-12-25 13:25:16,234 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f41a0172600>, 'Connection to ec2-54-221-47-33.compute-1.amazonaws.com timed out. (connect timeout=120)')': /api/2.0/mlflow/runs/create
[ 2024-12-25 13:27:34,000 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f41a0172f60>, 'Connection to ec2-54-221-47-33.compute-1.amazonaws.com timed out. (connect timeout=120)')': /api/2.0/mlflow/runs/create
[ 2024-12-25 13:29:58,609 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f4190769910>, 'Connection to ec2-54-221-47-33.compute-1.amazonaws.com timed out. (connect timeout=120)')': /api/2.0/mlflow/runs/create
