[ 2024-12-25 12:48:26,498 ] 39 root - INFO - Start data Ingestion
[ 2024-12-25 12:48:36,752 ] 65 root - INFO - Performed train test split on the dataframe
[ 2024-12-25 12:48:36,753 ] 67 root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[ 2024-12-25 12:48:36,764 ] 75 root - INFO - Exporting train and test file path.
[ 2024-12-25 12:48:37,196 ] 84 root - INFO - Exported train and test file path.
[ 2024-12-25 12:48:37,205 ] 42 root - INFO - Data Ingestion completed and artifact: DataIngestionArtifact(trained_file_path='Artifacts/12_25_2024_12_18_46/data_ingestion/ingested/train.csv', test_file_path='Artifacts/12_25_2024_12_18_46/data_ingestion/ingested/test.csv')
[ 2024-12-25 12:48:37,247 ] 52 root - INFO - Initiate the data Validation
[ 2024-12-25 12:48:45,256 ] 33 root - INFO - Required number of columns:2
[ 2024-12-25 12:48:45,258 ] 34 root - INFO - Data frame has columns:1
[ 2024-12-25 12:48:45,258 ] 33 root - INFO - Required number of columns:2
[ 2024-12-25 12:48:45,259 ] 34 root - INFO - Data frame has columns:1
[ 2024-12-25 12:48:45,417 ] 55 root - INFO - Entered initiate_data_transformation method of DataTransformation class
[ 2024-12-25 12:48:45,418 ] 57 root - INFO - Starting data transformation
[ 2024-12-25 12:48:45,517 ] 45 root - INFO - Initialise KNNImputer with {'missing_values': nan, 'n_neighbors': 3, 'weights': 'uniform'}
[ 2024-12-25 12:48:45,634 ] 51 root - INFO - Entered the save_object method of MainUtils class
[ 2024-12-25 12:48:45,686 ] 55 root - INFO - Exited the save_object method of MainUtils class
[ 2024-12-25 12:48:45,686 ] 51 root - INFO - Entered the save_object method of MainUtils class
[ 2024-12-25 12:48:45,725 ] 55 root - INFO - Exited the save_object method of MainUtils class
[ 2024-12-25 13:01:31,210 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb0244a3410>, 'Connection to ec2-54-221-47-33.compute-1.amazonaws.com timed out. (connect timeout=120)')': /api/2.0/mlflow/runs/create
[ 2024-12-25 13:03:42,902 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb0243a6570>, 'Connection to ec2-54-221-47-33.compute-1.amazonaws.com timed out. (connect timeout=120)')': /api/2.0/mlflow/runs/create
